import DashboardLayout from "@/components/DashboardLayout";
import { AIChatBox, type Message } from "@/components/AIChatBox";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { isSameLocalDay, itemKindLabel } from "@shared/calendar";
import { AlertTriangle, ArrowLeft, BookOpen, BriefcaseBusiness, CalendarDays, Check, CheckCircle2, ClipboardList, Clock3, FileText, GraduationCap, HeartPulse, Home, Inbox, Link2, ListChecks, Plus, ReceiptText, ShoppingCart, Sparkles, Users, WalletCards, Wrench, type LucideIcon } from "lucide-react";
import React from "react";
import { Link, useRoute } from "wouter";
import { toast } from "sonner";

const contextCards: Record<string, Array<[string, string, LucideIcon]>> = {
  casa: [["Compras", "Montar minha lista de compras da casa", ShoppingCart], ["Rotina semanal", "Organizar as atividades domésticas desta semana", Sparkles], ["Manutenção", "Criar lembretes de manutenção da casa", Wrench], ["Contas", "Listar as contas e vencimentos da casa", ReceiptText], ["Limpeza", "Montar uma rotina de limpeza realista para a casa", Sparkles], ["Organização", "Organizar pendências de organização da casa", Home], ["Lavanderia", "Planejar as roupas e a lavanderia desta semana", Sparkles], ["Plantas e pets", "Criar lembretes de cuidados com plantas e pets", Home]],
  faculdade: [["Aulas", "Organizar minhas aulas e horários da faculdade", BookOpen], ["Provas", "Listar minhas próximas provas e como estudar", ClipboardList], ["Trabalhos", "Organizar meus trabalhos e prazos da faculdade", FileText], ["Leituras", "Planejar minhas leituras da faculdade", BookOpen]],
  trabalho: [["Prioridades", "Organizar minhas prioridades de trabalho", BriefcaseBusiness], ["Reuniões", "Listar minhas reuniões e preparações do trabalho", Users], ["Entregas", "Organizar minhas entregas e prazos do trabalho", ClipboardList], ["Acompanhamento", "Criar um acompanhamento das pendências do trabalho", ListChecks]],
  família: [["Aniversários", "Organizar aniversários e datas importantes da família", Users], ["Cuidados", "Organizar os cuidados e compromissos da família", HeartPulse], ["Compromissos", "Listar os compromissos compartilhados da família", CalendarDays], ["Comunicação", "Criar lembretes para falar com pessoas da família", Users]],
  "vida adulta": [["Documentos", "Organizar meus documentos e burocracias", FileText], ["Saúde", "Organizar consultas e cuidados com a saúde", HeartPulse], ["Finanças", "Listar minhas tarefas financeiras e vencimentos", WalletCards], ["Pendências", "Organizar as pendências importantes da vida adulta", ListChecks]],
  "tarefas gerais": [["Capturar", "Organizar minhas tarefas soltas", ListChecks], ["Próximos passos", "Transformar minhas ideias em próximos passos", Sparkles], ["Revisão", "Fazer uma revisão das tarefas pendentes", ClipboardList], ["Priorizar", "Me ajudar a priorizar o que precisa ser feito", ListChecks]],
};

const colors: Record<string, string> = {
  lavender: "bg-violet-100 text-violet-700 border-violet-200",
  blue: "bg-blue-100 text-blue-700 border-blue-200",
  rose: "bg-rose-100 text-rose-700 border-rose-200",
  amber: "bg-amber-100 text-amber-700 border-amber-200",
  teal: "bg-teal-100 text-teal-700 border-teal-200",
  sage: "bg-emerald-100 text-emerald-700 border-emerald-200",
};

function timeLabel(timestamp: number) { return new Date(timestamp).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" }); }
function dateLabel(timestamp: number) { return new Date(timestamp).toLocaleDateString("pt-BR", { weekday: "long", day: "2-digit", month: "long" }); }

export default function Group() {
  const [, params] = useRoute("/groups/:id");
  const groupId = Number(params?.id);
  const utils = trpc.useUtils();
  const { data, isLoading, isError } = trpc.planner.groupSnapshot.useQuery({ groupId }, { enabled: Number.isInteger(groupId) && groupId > 0 });
  const sendMessage = trpc.planner.sendMessage.useMutation({ onSuccess: () => utils.planner.groupSnapshot.invalidate({ groupId }), onError: () => toast.error("Não consegui processar essa mensagem agora.") });
  const clearChat = trpc.auth?.clearChat?.useMutation ? trpc.auth.clearChat.useMutation({ onSuccess: () => { utils.planner.groupSnapshot.invalidate({ groupId }); toast.success("Conversa limpa"); }, onError: error => toast.error(error.message) }) : { mutate: () => undefined };
  const submodulesQuery = trpc.planner.submodules.useQuery({ groupId }, { enabled: Number.isInteger(groupId) && groupId > 0 });
  const createSubmodule = trpc.planner.createSubmodule.useMutation({ onSuccess: () => { setNewSubmodule(""); utils.planner.submodules.invalidate({ groupId }); }, onError: () => toast.error("Não consegui criar esse subtema agora.") });
  const [newSubmodule, setNewSubmodule] = React.useState("");
  const updateStatus = trpc.planner.updateStatus.useMutation({ onSuccess: () => utils.planner.groupSnapshot.invalidate({ groupId }) });
  const messages: Message[] = (data?.messages ?? []).map(message => ({ role: message.role, content: message.content }));
  const items = data?.items ?? [];
  const contextKey = data?.group?.name.trim().toLowerCase() ?? "";
  const cards = contextCards[contextKey] ?? [];
  const summaryConfig: Record<string, { title: string; intro: string; nextLabel: string }> = {
    faculdade: { title: "Resumo acadêmico", intro: "Uma leitura rápida da sua vida na faculdade.", nextLabel: "próximo compromisso" },
    trabalho: { title: "Resumo profissional", intro: "Uma leitura rápida do que pede atenção no trabalho.", nextLabel: "próximo compromisso" },
    casa: { title: "Resumo da casa", intro: "Uma leitura rápida das responsabilidades domésticas.", nextLabel: "próxima atividade" },
    família: { title: "Resumo da família", intro: "Uma leitura rápida dos cuidados e compromissos da família.", nextLabel: "próximo compromisso" },
    "vida adulta": { title: "Resumo da vida adulta", intro: "Uma leitura rápida das pendências práticas da vida.", nextLabel: "próxima pendência" },
    "tarefas gerais": { title: "Resumo das tarefas", intro: "Uma leitura rápida do que está aguardando sua atenção.", nextLabel: "próximo item" },
  };
  const groupSummary = summaryConfig[contextKey] ?? { title: `Resumo de ${data?.group?.name ?? "grupo"}`, intro: "Uma leitura rápida deste espaço.", nextLabel: "próximo item" };
  const groupTasks = items.filter(item => item.kind === "task");
  const groupAppointments = items.filter(item => item.kind === "appointment");
  const groupPending = groupTasks.filter(item => item.status === "planned");
  const groupOverdue = groupPending.filter(item => item.plannedAt < Date.now());
  const groupCompleted = groupTasks.filter(item => item.status === "completed");
  const nextAppointment = groupAppointments.filter(item => item.status === "planned" && item.plannedAt >= Date.now()).sort((a, b) => a.plannedAt - b.plannedAt)[0];
  const nextTask = groupPending.filter(item => item.plannedAt >= Date.now()).sort((a, b) => a.plannedAt - b.plannedAt)[0];
  const groupAttention = [...groupOverdue, ...groupPending.filter(item => item.detailsNeeded && item.plannedAt >= Date.now())].slice(0, 4);
  const roots = items.filter(item => item.kind === "appointment" || !item.parentItemId);
  const childrenFor = (parentId: number) => items.filter(item => item.parentItemId === parentId || (item.kind === "task" && !item.parentItemId && items.some(parent => parent.id !== item.id && parent.kind === "appointment" && parent.notes === "Rotina recorrente" && isSameLocalDay(parent.plannedAt, item.plannedAt))));

  if (isError || !data?.group) return <DashboardLayout><div role="alert" className="mx-auto max-w-xl rounded-3xl bg-white p-8 text-center shadow-sm"><h1 className="font-display text-2xl font-semibold text-slate-900">Grupo não encontrado</h1><p className="mt-2 text-sm text-slate-500">Esse grupo pode ter sido removido ou não pertence à sua conta.</p><Link href="/"><Button className="mt-5">Voltar ao planejamento</Button></Link></div></DashboardLayout>;

  return <DashboardLayout><div className="mx-auto min-h-[calc(100vh-2rem)] max-w-[1480px] space-y-5 pb-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/"><Button variant="ghost" size="sm" className="mb-3 -ml-3 gap-2 text-slate-500"><ArrowLeft className="size-4" />Planejamento geral</Button></Link><div className="flex items-center gap-3"><span className={cn("rounded-full border px-3 py-1 text-xs font-semibold", colors[data.group.color] ?? colors.sage)}>{data.group.name}</span><span className="text-xs uppercase tracking-[0.18em] text-slate-400">espaço do grupo</span></div><h1 className="mt-3 font-display text-3xl font-semibold tracking-tight text-slate-900 sm:text-4xl">Tudo sobre {data.group.name}</h1><p className="mt-2 text-sm text-slate-500">Converse aqui somente sobre este grupo. Os registros criados ficam organizados nesta visão.</p></div><Link href="/calendar"><Button variant="outline" className="w-fit gap-2 bg-white"><CalendarDays className="size-4" />Agenda completa</Button></Link></header>
    {<Card className="border-violet-100 bg-violet-50/50 shadow-sm"><CardHeader className="px-6 pb-3 pt-5"><CardTitle className="flex items-center gap-2 text-base text-slate-800"><GraduationCap className="size-4 text-violet-600" />{groupSummary.title}</CardTitle><p className="mt-1 text-xs text-slate-500">{groupSummary.intro}</p></CardHeader><CardContent className="space-y-4 px-6 pb-5"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/80 p-3"><p className="text-2xl font-semibold text-slate-900">{groupPending.length}</p><p className="text-xs text-slate-500">pendentes</p></div><div className="rounded-2xl bg-rose-50/80 p-3"><p className="text-2xl font-semibold text-slate-900">{groupOverdue.length}</p><p className="text-xs text-rose-700">atrasados</p></div><div className="rounded-2xl bg-emerald-50/80 p-3"><p className="text-2xl font-semibold text-slate-900">{groupCompleted.length}</p><p className="text-xs text-emerald-700">concluídos</p></div></div><div className="grid gap-3 md:grid-cols-2"><div className="rounded-2xl border border-white/80 bg-white/75 p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-violet-700">próximo compromisso</p><p className="mt-2 text-sm font-semibold text-slate-800">{nextAppointment?.title ?? "Nenhum compromisso próximo"}</p>{nextAppointment && <p className="mt-1 text-xs text-slate-500">{dateLabel(nextAppointment.plannedAt)} · {timeLabel(nextAppointment.plannedAt)}</p>}{nextTask && <p className="mt-3 border-t border-slate-100 pt-2 text-xs text-slate-500"><span className="font-semibold text-slate-700">Próxima tarefa:</span> {nextTask.title}</p>}</div><div className="rounded-2xl border border-white/80 bg-white/75 p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-violet-700">o que exige atenção</p>{groupAttention.length ? <div className="mt-2 space-y-1">{groupAttention.map(item => <p key={item.id} className="flex items-center gap-2 text-xs text-slate-700"><AlertTriangle className="size-3 text-amber-500" />{item.title}</p>)}</div> : <p className="mt-2 text-xs text-slate-500">Nenhuma pendência crítica.</p>}</div></div></CardContent></Card>}
    {cards.length > 0 && <Card className="border-amber-100 bg-amber-50/60 shadow-sm"><CardHeader className="px-6 pb-3 pt-5"><CardTitle className="flex items-center gap-2 text-base text-slate-800"><Sparkles className="size-4 text-amber-600" />Ideias para {data.group.name}</CardTitle><p className="mt-1 text-xs text-slate-500">Comece por uma área e eu organizo os detalhes em tarefas, compromissos ou lembretes.</p></CardHeader><CardContent className="grid gap-3 px-6 pb-5 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, prompt, Icon]) => <button type="button" key={label} onClick={() => sendMessage.mutate({ content: prompt, groupId })} className="rounded-2xl border border-white/80 bg-white/80 p-4 text-left transition hover:-translate-y-0.5 hover:border-amber-200 hover:bg-white"><span className="flex size-9 items-center justify-center rounded-xl bg-white text-amber-600 shadow-sm"><Icon className="size-4" /></span><p className="mt-3 text-sm font-semibold text-slate-800">{label}</p><p className="mt-1 text-xs leading-5 text-slate-500">Conversar sobre isso</p></button>)}</CardContent></Card>}
    <Card className="border-slate-200/80 bg-white/90 shadow-sm"><CardHeader className="px-6 pb-3 pt-5"><CardTitle className="flex items-center gap-2 text-base text-slate-800"><Plus className="size-4 text-emerald-600" />Meus subtemas</CardTitle><p className="mt-1 text-xs text-slate-500">Crie tópicos com os nomes que fazem sentido para você.</p></CardHeader><CardContent className="space-y-3 px-6 pb-5"><form className="flex flex-col gap-2 sm:flex-row" onSubmit={event => { event.preventDefault(); if (newSubmodule.trim()) createSubmodule.mutate({ groupId, name: newSubmodule.trim() }); }}><Input value={newSubmodule} onChange={event => setNewSubmodule(event.target.value)} placeholder="Ex.: TCC, Projeto X, Academia" aria-label="Nome do novo subtema" /><Button type="submit" disabled={createSubmodule.isPending || newSubmodule.trim().length < 2} className="gap-2"><Plus className="size-4" />Criar subtema</Button></form>{submodulesQuery.data?.length ? <div className="flex flex-wrap gap-2">{submodulesQuery.data.map(module => <Link key={module.id} href={`/groups/${groupId}/module/${encodeURIComponent(module.name)}`}><Badge variant="outline" className="cursor-pointer border-emerald-200 bg-emerald-50 px-3 py-1 text-emerald-800 hover:bg-emerald-100">{module.name}</Badge></Link>)}</div> : <p className="text-xs text-slate-400">Ainda não há subtemas personalizados neste grupo.</p>}</CardContent></Card>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(420px,0.9fr)]">
      <Card className="overflow-hidden border-emerald-100/80 bg-white/90 shadow-[0_20px_60px_-40px_rgba(15,118,110,0.35)]"><CardHeader className="border-b border-slate-100 px-6 py-5"><CardTitle className="flex items-center gap-2 text-base text-slate-800"><Sparkles className="size-4 text-emerald-600" />Conversa de {data.group.name}</CardTitle><p className="mt-1 text-xs text-slate-500">A assistente usa este grupo como contexto padrão.</p></CardHeader><CardContent className="p-0"><AIChatBox onClear={() => { if (window.confirm("Limpar o histórico desta conversa? Os registros do grupo continuarão na agenda.")) clearChat.mutate({ groupId }); }} messages={messages} onSendMessage={(content) => sendMessage.mutate({ content, groupId })} isLoading={sendMessage.isPending} height="560px" placeholder={`Ex.: adicionar uma tarefa em ${data.group.name}`} emptyStateMessage={`Ainda não há conversa em ${data.group.name}. Comece por aqui.`} suggestedPrompts={cards.length > 0 ? cards.slice(0, 3).map(card => card[1]) : [`O que tenho em ${data.group.name}?`, "Adicionar uma tarefa para amanhã", "Não consegui concluir isso"]} /></CardContent></Card>
      <Card className="border-slate-200/80 bg-white/90 shadow-sm"><CardHeader className="px-6 pb-3 pt-5"><CardTitle className="flex items-center gap-2 text-base text-slate-800"><CalendarDays className="size-4 text-emerald-600" />Planejamento do grupo</CardTitle><p className="mt-1 text-xs text-slate-500">{items.length ? `${items.length} registro${items.length === 1 ? "" : "s"} neste espaço` : "Nenhum registro neste espaço ainda"}</p></CardHeader><CardContent className="px-4 pb-5">{isLoading ? <div className="space-y-3"><div className="h-16 animate-pulse rounded-2xl bg-slate-100" /><div className="h-16 animate-pulse rounded-2xl bg-slate-100" /></div> : roots.length ? <div className="space-y-3">{roots.sort((a, b) => a.plannedAt - b.plannedAt).map(item => { const children = childrenFor(item.id).filter(child => child.id !== item.id); return <div key={item.id} className={cn("rounded-2xl border p-3", item.kind === "appointment" ? "border-sky-100 bg-sky-50/50" : "border-slate-100 bg-white")}><div className="flex items-start gap-3"><button aria-label={item.status === "completed" ? "Item concluído" : `Concluir ${item.title}`} onClick={() => updateStatus.mutate({ id: item.id, status: item.status === "completed" ? "skipped" : "completed" })} className={cn("mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full border-2", item.status === "completed" ? "border-emerald-500 bg-emerald-500 text-white" : "border-slate-300")}>{item.status === "completed" && <Check className="size-3" />}</button><div className="min-w-0 flex-1"><p className={cn("text-sm font-semibold text-slate-800", item.status === "completed" && "line-through opacity-60")}>{item.title}</p><div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><Clock3 className="size-3" />{timeLabel(item.plannedAt)}</span><Badge variant="outline" className="border-slate-200 bg-white text-[10px]">{itemKindLabel(item.kind)}</Badge></div><p className="mt-1 text-[11px] text-slate-400">{dateLabel(item.plannedAt)} · {item.durationMinutes} min</p></div></div>{children.length > 0 && <div className="mt-3 space-y-1 border-l-2 border-emerald-200 pl-4"><p className="mb-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-emerald-700">Tarefas deste compromisso</p>{children.map(child => <div key={child.id} className="flex items-center gap-2 rounded-xl bg-white/80 px-2 py-2 text-xs text-slate-600"><Link2 className="size-3 text-emerald-500" />{child.title}<span className="ml-auto text-[10px] text-slate-400">{timeLabel(child.plannedAt)}</span></div>)}</div>}</div>})}</div> : <div className="rounded-2xl bg-emerald-50/60 px-5 py-10 text-center"><Inbox className="mx-auto size-7 text-emerald-400" /><p className="mt-3 text-sm font-medium text-slate-700">Este grupo ainda está livre.</p><p className="mt-1 text-xs text-slate-500">Use a conversa ao lado para começar.</p></div>}</CardContent></Card>
    </div>
  </div></DashboardLayout>;
}
